---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.9
  sha1: 3d6168823f5a8aa6b7427429bc727103e15e27af
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=60
  sha1: 8e40a9ff892204007889037f094a1b0d23777058

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262.12
    sha1: 90e9825b814da801e1aff7b02508fdada8e155cb
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk: {size: 25_000, type: gp2}
    availability_zone: REP_VAR_AZ # <--- Replace with Availability Zone

disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
- range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.2]
    cloud_properties: {subnet: REP_VAR_SUBNET_ID } # <--- Replace with Subnet ID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

templates:
- {name: nats, release: bosh}
- {name: postgres, release: bosh}
- {name: blobstore, release: bosh}
- {name: director, release: bosh}
- {name: health_monitor, release: bosh}
- {name: registry, release: bosh}
- {name: aws_cpi, release: bosh-aws-cpi}

resource_pool: vms
persistent_disk_pool: disks

networks:
- name: private
  atatic_ips: [10.0.0.6]
  default: [dns, gateway]
- name: public
  static_ips: [REP_VAR_EIP] # <--- Replace with Elastic IP

properties:
  nats:
    address: 127.0.0.1
    user: nats
    password: nats-password

  postgres: &db
    listen_address: 127.0.0.1
    host: 127.0.0.1
    user: postgres
    password: postgres-password
    database: bosh
    adapter: postgres

  registry:
    address: 10.0.0.6
    host: 10.0.0.6
    db: *db
    http: {user: admin, password: admin, port: 25777}
    username: admin
    password: admin
    port: 25777

  blobstore:
    address: 10.0.0.6
    port: 25250
    provider: dav
    director: {user: director, password: director-password}
    agent: {user: agent, password: agent-password}

  director:
    address: 127.0.0.1
    name: my-bosh
    db: *db
    cpi_job: aws_cpi
    max_threads: 10
    user_management:
      provider: local
      local:
        users:
        - {name: admin, password: admin}
        - {name: hm, password: hm-password}

  hm:
    director_account: {user: hm, password: hm-password}
    resurrector_enabled: true

  aws: &aws
    access_key_id: REP_VAR_AWS_KEY_ID # <--- Replace with AWS Access Key ID
    secret_access_key: REP_VAR_AWS_SECRET_ACCESS_KEY # <--- Replace with AWS Secret Key
    default_key_name: REP_VAR_KEY_NAME # <--- Replace with the key name
    default_security_groups: [training_sg]
    region: REP_VAR_AWS_REGION  # <--- Replace with Region

  agent: {mbus: "nats://nats:nats-password@10.0.0.6:4222"}

  ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

ssh_tunnel:
  host: REP_VAR_EIP # <--- Replace with your Elastic IP address
  port: 22
  user: vcap
  private_key: ./bosh.pem # Path relative to this manifest file

mbus: "https://mbus:mbus-password@REP_VAR_EIP:6868" # <--- Replace with Elastic IP

properties:
  aws: *aws
  agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
  blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
  ntp: *ntp
